source $HOME/.vim/config/shortcuts.vim
source $HOME/.vim/config/bundles.vim

"load color scheme with syntax
syntax enable
set background=dark
colorscheme solarized

set number "show line numbers
set cpoptions+=$
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent
set linebreak
set clipboard=unnamed
set backspace=indent,eol,start

"search options
set hlsearch "highlight search
set incsearch
set smartcase
set ignorecase

filetype plugin indent on

" display a warning if file encoding isnt utf-8
set statusline=
set statusline+=%#warningmsg#
" set the format of the status line
set statusline+=%*
set statusline+=%t              "filename
set statusline+=%m              "modified flag
set statusline+=%r              "read only flag
set statusline+=\ \%y           "filetype
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%=              "left/right separator
set statusline+=%*              "show the errors/warning in the status line
set statusline+=%#warningmsg#
set statusline+=%*
set statusline+=%=              "left/right separator
set statusline+=%h\ \           "help file flag
set statusline+=[%l,%c]         "cursor line,column
set statusline+=\ \|%L\ lines\| "total lines
set statusline+=\ %P            "percent through file
set laststatus=2

"set different cursor when on insert mode - works for iTerm only
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
