" vim: filetype=vim
call pathogen#infect()

"load color scheme with syntax
syntax enable
set background=dark
colorscheme solarized

set number "show line numbers
set cpoptions+=$
set hlsearch "highlight search
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent
set linebreak
set clipboard=unnamed

filetype plugin indent on

" display a warning if file encoding isnt utf-8
set statusline=
set statusline+=%#warningmsg#
" set the format of the status line
set statusline+=%*
set statusline+=%t              "filename
set statusline+=%m              "modified flag
set statusline+=%r              "read only flag
set statusline+=\ \%y           "filetype
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%=              "left/right separator
set statusline+=%*              "show the errors/warning in the status line
set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set statusline+=%=              "left/right separator
set statusline+=%h\ \           "help file flag
set statusline+=[%l,%c]         "cursor line,column
set statusline+=\ \|%L\ lines\| "total lines
set statusline+=\ %P            "percent through file
set laststatus=2

source $HOME/.vim/config/shortcuts
